# Generated by Django 4.2 on 2023-04-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('publish_date', models.DateField(null=True)),
                ('cover_art', models.URLField(max_length=300, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
