# Generated by Django 4.2 on 2023-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='djangojams.genre'),
        ),
    ]
