# Generated by Django 4.2 on 2023-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0003_album_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=1000, null=True)),
                ('image', models.URLField(max_length=300, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
