# Generated by Django 4.2 on 2023-04-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0005_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
