# Generated by Django 4.2 on 2023-04-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0006_rename_album_id_song_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangojams.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangojams.song')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
