# Generated by Django 4.2 on 2023-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0012_delete_artist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='genre', to='djangojams.genre'),
        ),
    ]
