# Generated by Django 4.2 on 2023-04-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangojams', '0013_alter_album_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='artist',
        ),
    ]
